A&M:
  nlay: 100
  ptop: 1.0e-6
  pbot: 1000.0

  mu_z: 0.00
  Tirr: 1000.0
  Tint: 500.0
  k_v: 4.0e-3
  k_ir: 1.0e-2 
  grav: 1000.0
  met: 0.0
  kappa: 0.2857
  mu: 2.3

  Guillot: True
  Parmentier: False

  fsed: 0.1
  sigma: 2.0
  alpha: 1.3
  al: 1.0
  Kzz: 1.0e+8

  bg_sp: ['H2','He']
  bg_VMR: [0.85, 0.15]
  bg_mw: [2.016, 4.00]

  cld_sp: ['MgSiO3']
  cld_mw: [100.39]
  qv0: [3.548e-5]
  rho_d: [3.2]

sat_adjust:

  mu_z: 1.0

moment:
  mu_z: 1.0