A&M:
  nlay: 100
  ptop: 1.0e-3
  pbot: 1000.0

  mu_z: 0.577
  Tirr: 1200.0
  Tint: 400.0
  k_v: 4.0e-3
  k_ir: 1.0e-2 
  grav: 2000.0
  met: 0.0
  kappa: 0.2857
  mu: 2.33

  Guillot: False
  Parmentier: True
  adibat_corr: True

  al: 1.0
  Kzz: 1.0e+10

  bg_sp: ['H2','He']
  bg_VMR: [0.85,0.15]
  bg_mw: [2.016,4.00]
  bg_d: [2.827e-8,2.511e-8]
  bg_LJ: [59.7,10.22]

  cld_sp: ['Fe','MgSiO3']
  rho_d: [7.87,3.2]
  cld_mw: [55.845,100.39]
  fsed: [1.0, 1.0]
  sigma: [2.0, 2.0]
  alpha: [1.3, 1.3]

  vap_mw: [55.845,100.39]
  vap_VMR: [2.88e-5,3.55e-5]

tracer_saturation_adjustment:

  nlay: 100
  ptop: 1.0e-3
  pbot: 1000.0

  mu_z: 0.577
  Tirr: 1200.0
  Tint: 400.0
  k_v: 4.0e-3
  k_ir: 1.0e-2 
  grav: 2000.0
  met: 0.0
  kappa: 0.2857
  mu: 2.33

  Guillot: False
  Parmentier: True
  adibat_corr: True

  Kzz: 1.0e+10

  n_step: 10000
  t_step: 1000.0

  bg_sp: ['H2','He']
  bg_VMR: [0.85,0.15]
  bg_mw: [2.016,4.00]
  bg_d: [2.827e-8,2.511e-8]
  bg_LJ: [59.7,10.22]

  cld_sp: ['Fe','MgSiO3']
  rho_d: [7.87,3.2]
  cld_mw: [55.845,100.39]
  cld_r_m: [30.0,30.0]
  cld_sig: [2.0,2.0]
  cld_tau_c: [100.0,100.0]

  vap_mw: [55.845,100.39]
  vap_VMR: [2.88e-5,3.55e-5]

two_moment_mixed:

  nlay: 100
  ptop: 1.0e-3
  pbot: 1000.0

  mu_z: 0.577
  Tirr: 1200.0
  Tint: 400.0
  k_v: 4.0e-3
  k_ir: 1.0e-2 
  grav: 2000.0
  met: 0.0
  kappa: 0.2857
  mu: 2.33

  Guillot: False
  Parmentier: True
  adibat_corr: True

  Kzz: 1.0e+10

  n_step: 10000
  t_step: 1000.0

  bg_sp: ['H2','He']
  bg_VMR: [0.85,0.15]
  bg_mw: [2.016,4.00]
  bg_d: [2.827e-8,2.511e-8]
  bg_LJ: [59.7,10.22]

  cld_sp: ['TiO2' ,'Fe','MgSiO3']
  rho_d: [4.23, 7.87, 3.2]
  cld_mw: [79.866, 55.845, 100.39]
  nuc_sp: [True, False, False]

  vap_mw: [79.866 , 55.845, 100.39]
  vap_VMR: [9.33e-8, 2.88e-5, 3.55e-5]
